---
title: "Iris Dataset Analysis"
author: "Miles Peña"
date: "2024-01-21"
output:
  pdf_document: default
  html_document: default
---

# Iris Analysis

```{r}
# load iris

library(datasets)
data(iris)

```

``` {r}
# new iris variable

newIrisVar <- iris

```

## Average Sepal Length by Species

``` {r}
# load dplyr and group by species

library(dplyr)
newIrisVar %>% group_by(Species) %>% 
summarise(Avg_Sepal_Length = mean(Sepal.Length))

```

``` {r include = FALSE}
# load ggplot do not include

library(ggplot2)

```

## Visualizations

``` {r}
# histograms and boxplots for sepal length, sepal width, petal length and petal width

# Sepal Length
sepal_length <- ggplot(newIrisVar, aes(x = Sepal.Length, fill = Species)) +
geom_histogram(position = "identity", alpha = 0.5, bins = 30) +
geom_boxplot(width = 0.1)
sepal_length

# Sepal Width
sepal_width <- ggplot(newIrisVar, aes(x = Sepal.Width, fill = Species)) +
geom_histogram(position = "identity", alpha = 0.5, bins = 30) +
geom_boxplot(width = 0.1)
sepal_width

# Petal Length
petal_length <- ggplot(newIrisVar, aes(x = Petal.Length, fill = Species)) +
geom_histogram(position = "identity", alpha = 0.5, bins = 30) +
geom_boxplot(width = 0.1)
petal_length

# Petal Width
petal_width <- ggplot(newIrisVar, aes(x = Petal.Width, fill = Species)) +
geom_histogram(position = "identity", alpha = 0.5, bins = 30) +
geom_boxplot(width = 0.1)
petal_width

# Based on the histograms/boxplots, the species setosa has the smallest lengths of sepals but has the widest sepals. Setosa also has the smallest petal widths and lengths in comparison to the other two. Versicolor, in comparison to the two, has mediium length sepals and the smallest sepal widths. It also holds the middle ground for both petal lenght and width. Virginica has the longest sepal lenghts, petal lenghts, and the widest petal width. Its sepal width lies at about the middle in comparison to the other two. 

```

